##############################################################################
##               ubuntu 18.04 with cuda 10.0 & cudnn 7.4.2.24               ##
##############################################################################
# https://gitlab.com/nvidia/cuda/blob/master/dist/ubuntu16.04/10.1/devel/cudnn7/Dockerfile

FROM nvidia/cuda:10.0-devel-ubuntu18.04

ENV CUDNN_VERSION 7.4.2.24

# change server for apt-get
RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn7=$CUDNN_VERSION-1+cuda10.0 \
    libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 \
    && \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*

ENV PATH /usr/local/cuda-10.0/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda-10.0/lib64:${LD_LIBRARY_PATH}

##############################################################################
##                Python3 & matplotlib & pip & opencv & tf                  ##
##############################################################################

RUN apt update
RUN echo y | apt install python3
RUN echo y | apt install python3-pip
RUN python3 -m pip install --upgrade pip setuptools

RUN pip3 install scipy==1.3.3
RUN pip3 install requests==2.22.0
RUN pip3 install Pillow==6.2.1
RUN pip3 install numpy
RUN pip3 install tensorboard
RUN pip3 install cython
RUN pip3 install lmdb
RUN pip3 install moviepy
RUN pip3 install opencv-python
RUN pip3 install ninja
RUN pip3 install tensorboardX
RUN pip3 install wandb

RUN pip3 install matplotlib
RUN pip3 install scikit-learn
RUN pip3 install scikit-image

RUN pip3 install tensorflow-gpu==1.15.0
RUN pip3 install torch torchvision
RUN pip3 install keras==2.2.4


##############################################################################
##                                  git                                     ##
##############################################################################
RUN apt update
RUN echo y | apt install git


##############################################################################
##                            opencv2 error                                 ##
##############################################################################
RUN apt update
RUN echo y | apt install libgl1-mesa-glx

##############################################################################
##                              visualization                               ##
##############################################################################
RUN pip3 install pydot
# RUN pip3 install graphviz
RUN pip3 install PyGLM
RUN pip3 install PySide2
RUN pip3 install pyopengl
RUN pip3 install PyOpenGL_accelerate
RUN echo y | apt install graphviz
RUN echo y | apt install freeglut3 
RUN echo y | apt install freeglut3-dev
RUN apt update

# ENV CUDA_VISIBLE_DEVICES = -1